spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=${internal.db-schema}&stringtype=UNSPECIFIED
    username: postgres
    password: postgres
  jpa:
    show-sql: true

liquibase:
  drop-first: false

logging:
  config: classpath:logback-local.xml
